### ISSUE TITLE
regarding the colors of rainbow 

### ISSUE THREAD

**Issue by keshav216** [k3shavv/Rainbow-Poem#4]
the colors mentioned in the rainbow poem are not correct. i am inserting an image of an actual rainbow so you can see for yourself
[this is a link](https://youtube.com)
![Capture](https://user-images.githubusercontent.com/67955546/87180087-7d203a80-c2fd-11ea-8603-6f387ba99416.PNG)

**Comment by k3shavv** [comment]
oh thanks for pointing out, i will do the needful
thanks again : )
